# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Cron job

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run_script:

    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: cd channelavailability-test && ./konssole/bin/Release/net7.0/linux-x64/publish/konssole soup
#      - name: Run job
#        run: bash cd channelavailability-test && ./konssole/bin/Release/net7.0/linux-x64/publish/konssole soup
